bahmni_batch_url: https://s3.amazonaws.com/endtb-artifacts/bahmni-endtb-batch/bahmni-endtb-batch-2.0.1-27.noarch.rpm
bahmni_endtb_batch_url: https://bamboo.pih-emr.org:81/bahmni-repo/bahmni-endtb-batch-2.4.1-32.noarch.rpm

